-- levels_data.lua —— 由 miliastra/tools/export-levels.mjs 从 src/levels.js 生成，**不要手改**。
--
-- ★ 与 levels.js 的唯一结构差异：level.makeSpine 是一个**函数**，跨语言传不过去，
--   所以换成 spineKind（0 = 螺旋，1 = 交叉桥）；与之配套的 level.layers 也换成
--   layersFromJunction（分层切在骨架的 junctionU 处）。
--
-- 关卡顺序：新手关在前，原本那四个核心关在后（= ALL_LEVELS 的顺序）。
-- 字段含义见 DESIGN.md §5.3 / §55 / §60，以及 docs/05-移植方案.md。

local M = {}

M.LEVELS = {
  {
    id = "t1-pair",
    name = "① 配对",
    short = "配对",
    spineKind = 0,
    layersFromJunction = false,
    railOrder = "spawn-inner",
    turns = 0.75,
    innerRatio = nil,
    prefill = 12,
    ballBudget = 12,
    scoreTarget = math.huge,
    still = true,
    centerChain = true,
    noClear = true,
    goal = "matchAll",
    speed = nil,
    startWpFrac = nil,
    bases = nil,
    script = nil,
    hint = { "球面颜色和字母互为反色 —— 打一颗反色的，就把它「读出」。", "这一关不用凑三颗：把 12 颗全读出来就过关。" },
  },
  {
    id = "t2-multiple",
    name = "② 三的倍数",
    short = "三的倍数",
    spineKind = 0,
    layersFromJunction = false,
    railOrder = "spawn-inner",
    turns = 0.75,
    innerRatio = nil,
    prefill = nil,
    ballBudget = 9,
    scoreTarget = math.huge,
    still = true,
    centerChain = true,
    noClear = false,
    goal = nil,
    speed = nil,
    startWpFrac = nil,
    bases = nil,
    script = "A1 A1 A1 A1 A0 U0 G0 C0 U0",
    hint = { "这一关开始要消球了：连着读出的球**必须是 3 的倍数**才能消。", "看徽章上的「还差 M」—— 差几颗就再补几颗。" },
  },
  {
    id = "t3-wrong",
    name = "③ 配错的代价",
    short = "配错的代价",
    spineKind = 0,
    layersFromJunction = false,
    railOrder = "spawn-inner",
    turns = 0.75,
    innerRatio = nil,
    prefill = nil,
    ballBudget = 12,
    scoreTarget = math.huge,
    still = true,
    centerChain = true,
    noClear = false,
    goal = nil,
    speed = nil,
    startWpFrac = nil,
    bases = nil,
    script = "A1 A2 A1 A0 U0 A0 U0 A0 U0 A0 U0 A0",
    hint = { "打错颜色 = 灰球。灰球**不会立刻炸** ——", "要等它左右两颗都已经读出、而且**状态一样**（都配对 / 都配错）时，才连它一起炸掉 3 颗。", "刚才那一炸就是这么来的。不扣分，但那一段白配了。" },
  },
  {
    id = "t4-insert",
    name = "④ 加球",
    short = "加球",
    spineKind = 0,
    layersFromJunction = false,
    railOrder = "spawn-inner",
    turns = 0.75,
    innerRatio = nil,
    prefill = 12,
    ballBudget = 12,
    scoreTarget = math.huge,
    still = true,
    centerChain = true,
    noClear = false,
    goal = nil,
    speed = nil,
    startWpFrac = nil,
    bases = { "A", "U" },
    script = nil,
    hint = { "按 Tab（手机点右下角）切到「加球」—— 往链里插一颗，序列的长度就变了。", "凑不成 3 的倍数时，这是除了消球之外的另一种调整手段。", "插错了按 R 重来。" },
  },
  {
    id = "t5-deadball",
    name = "⑤ 死球",
    short = "死球",
    spineKind = 0,
    layersFromJunction = false,
    railOrder = "spawn-inner",
    turns = 0.75,
    innerRatio = nil,
    prefill = nil,
    ballBudget = 9,
    scoreTarget = math.huge,
    still = true,
    centerChain = true,
    noClear = false,
    goal = nil,
    speed = nil,
    startWpFrac = nil,
    bases = { "A", "U" },
    script = "A1 A1 U0 A1 A1 A0 A0 A0 A0",
    hint = { "两段各 2 颗，中间夹着 1 颗没读的。", "★ 别急着配中间那颗：配了它，两段会并成 5 颗，反而更远。", "去把后面那几颗凑成一段；真踩了坑，就再补一颗到 6。" },
  },
  {
    id = "t6-cave",
    name = "⑥ 洞穴",
    short = "洞穴",
    spineKind = 0,
    layersFromJunction = false,
    railOrder = "spawn-inner",
    turns = nil,
    innerRatio = nil,
    prefill = nil,
    ballBudget = 22,
    scoreTarget = math.huge,
    still = false,
    centerChain = false,
    noClear = false,
    goal = nil,
    speed = 14,
    startWpFrac = 0.72,
    bases = { "A", "U" },
    script = "A U A U A U A U A U",
    hint = { "★ 到这里才有轨道：球会一直往洞穴爬，队头滚进去就扣一条命。", "它现在离洞口很近 —— 先把最前面那几颗消掉。" },
  },
  {
    id = "t7-mix",
    name = "⑦ 综合",
    short = "综合",
    spineKind = 0,
    layersFromJunction = false,
    railOrder = "spawn-inner",
    turns = nil,
    innerRatio = nil,
    prefill = 16,
    ballBudget = 36,
    scoreTarget = math.huge,
    still = false,
    centerChain = false,
    noClear = false,
    goal = nil,
    speed = 26,
    startWpFrac = nil,
    bases = nil,
    script = nil,
    hint = { "把前面学的都用上：反色配对、凑 3 的倍数、别去配 1-间隔的那颗。" },
  },
  {
    id = "spiral-inner",
    name = "螺旋 · 出球道在内",
    short = "螺旋·内",
    spineKind = 0,
    layersFromJunction = false,
    railOrder = "spawn-inner",
    turns = nil,
    innerRatio = nil,
    prefill = 14,
    ballBudget = 48,
    scoreTarget = math.huge,
    still = false,
    centerChain = false,
    noClear = false,
    goal = nil,
    speed = nil,
    startWpFrac = nil,
    bases = nil,
    script = nil,
    hint = nil,
  },
  {
    id = "cross-return",
    name = "交叉演示 · 遮挡与桥",
    short = "交叉桥",
    spineKind = 1,
    layersFromJunction = true,
    railOrder = "spawn-inner",
    turns = nil,
    innerRatio = nil,
    prefill = 16,
    ballBudget = 60,
    scoreTarget = math.huge,
    still = false,
    centerChain = false,
    noClear = false,
    goal = nil,
    speed = nil,
    startWpFrac = nil,
    bases = nil,
    script = nil,
    hint = nil,
  },
  {
    id = "endless",
    name = "无尽 · 无限出球",
    short = "无尽",
    spineKind = 0,
    layersFromJunction = false,
    railOrder = "spawn-inner",
    turns = nil,
    innerRatio = nil,
    prefill = 18,
    ballBudget = 0,
    scoreTarget = 500,
    still = false,
    centerChain = false,
    noClear = false,
    goal = nil,
    speed = nil,
    startWpFrac = nil,
    bases = nil,
    script = nil,
    hint = nil,
  },
}

function M.byId(id)
  for i = 1, #M.LEVELS do
    if M.LEVELS[i].id == id then return M.LEVELS[i] end
  end
  return nil
end

return M
